# render.yaml
services:
  - type: web
    name: springboot-app
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/tu-app.jar"
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://<HOST>:5432/<DBNAME>
      - key: SPRING_DATASOURCE_USERNAME
        value: <USER>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <PASS>
